# Generated by Django 2.2.7 on 2019-11-27 09:44

import advertisement.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Signaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('is_succeeded', models.BooleanField(blank=True, default=None, null=True)),
                ('profit', models.FloatField(blank=True, default=None, null=True)),
                ('start_date', models.DateField()),
                ('close_date', models.DateField()),
                ('expected_return', models.FloatField()),
                ('expected_risk', models.FloatField()),
                ('signaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Signaler')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=advertisement.utils.generate_random_token, max_length=32)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Signaler')),
            ],
        ),
    ]
